# Numpy Basics

### Install numpy

In [ ]:
#!pip3 install numpy

### Import numpy

In [ ]:
import numpy as np

### Initialise a ndarray from a python list

In [3]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [4]:
b = np.array([1, 2, 3, 4, 5])
b

array([1, 2, 3, 4, 5])

In [5]:
a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
a[0]

array([1, 2, 3])

### Some important methods to initialise ndarrays

In [7]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(4)

array([1.36882967e-316, 0.00000000e+000, 7.90505033e-323, 7.90505033e-323])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

### Generate a range of numbers from start to end with some step size

In [12]:
np.arange(2, 21, 4)

array([ 2,  6, 10, 14, 18])

### Generate k numbers from start to end

In [14]:
np.linspace(2, 21, 10)

array([ 2.        ,  4.11111111,  6.22222222,  8.33333333, 10.44444444,
       12.55555556, 14.66666667, 16.77777778, 18.88888889, 21.        ])

### Numpy array data type (dtype)

In [16]:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

### Delete add and sort elements

In [18]:
a = np.array([3, 4, 5, 2, 3,7, 1])

In [20]:
b = np.sort(a)
b

array([1, 2, 3, 3, 4, 5, 7])

#### List in python '+' will concatinate

In [21]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [30]:
a + b

array([ 6,  8, 10, 12])

In [32]:
a ** 2

array([ 1,  4,  9, 16])

In [38]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### Size Shape and dimention of an array

In [55]:
rubic_cupe = np.array([[["Y", "Y", "Y",], ["Y", "Y", "Y",], ["Y", "Y", "Y",]],
[["W", "W", "W",], ["W", "W", "W",], ["W", "W", "W",]],
[["Y", "Y", "Y",], ["Y", "Y", "Y",], ["Y", "Y", "Y",]],
[["Y", "Y", "Y",], ["Y", "Y", "Y",], ["Y", "Y", "Y",]],
[["Y", "Y", "Y",], ["Y", "Y", "Y",], ["Y", "Y", "Y",]],
[["Y", "Y", "Y",], ["Y", "Y", "Y",], ["Y", "Y", "Y",]],])

rubic_cupe

array([[['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']],

       [['W', 'W', 'W'],
        ['W', 'W', 'W'],
        ['W', 'W', 'W']],

       [['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']],

       [['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']],

       [['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']],

       [['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y'],
        ['Y', 'Y', 'Y']]], dtype='<U1')

In [56]:
rubic_cupe.shape

(6, 3, 3)

In [57]:
rubic_cupe.size

54

In [58]:
rubic_cupe.ndim

3

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Shape => (2, 3)
Size => 6
Dim => 2

In [54]:
x = a.shape
x

(2, 3)

In [44]:
a.size

6

In [45]:
a.ndim

2

A camera is recording at 30 frames per second and a resolution of 1000 X 786... What is the dimention of the video


(300, 1000, 786, 3)

### Reshape a  NP array

In [60]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
b = a.reshape(4, 5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Creating a New Axis 

In [87]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
a.shape

(10,)

In [89]:
a[0]

1

In [90]:
b = a[np.newaxis, :]
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [91]:
b.shape

(1, 10)

In [92]:
b[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
c = np.arange(1, 50)

### Transform a matrix

In [94]:
a = np.arange(1, 21).reshape(4, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [95]:
a.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [ ]:
(np.ones(25) * 3.14).reshape(5, 5)

In [ ]:
1 2 3 4 5 11 12 13 14 15 21 22 23 24 25 31 32 33 34 35 41 42 43 44 45

## Indexing and Slicing

In [99]:
a = np.array([11, 12, 13, 4, 5])

In [100]:
a[0]

11

expression[start index : end_index : step_size]

In [113]:
a[0 : 3]

array([11, 12, 13])

In [114]:
a[2:]

array([13,  4,  5])

In [115]:
a[:3]

array([11, 12, 13])

In [123]:
a = np.arange(1000)
np.concatenate((a[:6], a[-5:]))

array([  0,   1,   2,   3,   4,   5, 995, 996, 997, 998, 999])

### Funny broadcasting matrix example

In [144]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [145]:
b = np.zeros(25).reshape(5, 5)
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [146]:
b + a

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [147]:
c = (np.arange(0, 5) * 10).reshape(5, 1)

In [148]:
c

array([[ 0],
       [10],
       [20],
       [30],
       [40]])

In [149]:
(b + a + c)

array([[ 1.,  2.,  3.,  4.,  5.],
       [11., 12., 13., 14., 15.],
       [21., 22., 23., 24., 25.],
       [31., 32., 33., 34., 35.],
       [41., 42., 43., 44., 45.]])

In [150]:
(b + a + c).reshape(25)

array([ 1.,  2.,  3.,  4.,  5., 11., 12., 13., 14., 15., 21., 22., 23.,
       24., 25., 31., 32., 33., 34., 35., 41., 42., 43., 44., 45.])

#### simple and effective solution

In [152]:
np.arange(1, 46).reshape(9, 5)[::2].flatten()

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15, 21, 22, 23, 24, 25, 31, 32,
       33, 34, 35, 41, 42, 43, 44, 45])

### Relational Operation based slicing 

In [154]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [155]:
a[a <= 4]

array([1, 2, 3, 4])

In [156]:
a = np.arange(1000)

In [158]:
np.concatenate((a[:6], a[-5:]))

array([  0,   1,   2,   3,   4,   5, 995, 996, 997, 998, 999])

In [160]:
a[(a < 6) | (a > 995)]

array([  0,   1,   2,   3,   4,   5, 996, 997, 998, 999])

In [161]:
a[(a % 2 == 0) & (a % 3 == 0)]

array([  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,
        78,  84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144, 150,
       156, 162, 168, 174, 180, 186, 192, 198, 204, 210, 216, 222, 228,
       234, 240, 246, 252, 258, 264, 270, 276, 282, 288, 294, 300, 306,
       312, 318, 324, 330, 336, 342, 348, 354, 360, 366, 372, 378, 384,
       390, 396, 402, 408, 414, 420, 426, 432, 438, 444, 450, 456, 462,
       468, 474, 480, 486, 492, 498, 504, 510, 516, 522, 528, 534, 540,
       546, 552, 558, 564, 570, 576, 582, 588, 594, 600, 606, 612, 618,
       624, 630, 636, 642, 648, 654, 660, 666, 672, 678, 684, 690, 696,
       702, 708, 714, 720, 726, 732, 738, 744, 750, 756, 762, 768, 774,
       780, 786, 792, 798, 804, 810, 816, 822, 828, 834, 840, 846, 852,
       858, 864, 870, 876, 882, 888, 894, 900, 906, 912, 918, 924, 930,
       936, 942, 948, 954, 960, 966, 972, 978, 984, 990, 996])

In [163]:
k = (a % 2 == 0)
k

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,

In [179]:
a = np.arange(36).reshape(6, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [186]:
c = np.array([
    [1, 1, 1],
    [1, 2, 1],
    [1, 1, 1]
])

array([[42, 46, 50],
       [66, 70, 74],
       [90, 94, 98]])

### Sum elements in matrix

In [187]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [193]:
a.sum()

300

In [189]:
a.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [190]:
a.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

### Stacking Matrics

In [194]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(10, 19).reshape(3, 3)

In [195]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [196]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [197]:
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [198]:
np.hstack((a, b))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])